joy:
  ros__parameters:
    # device_name: /dev/input/joypad-f710
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2  # 2
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [9]  # 9 for PS4, 4 for Logitech F710
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 5.0
          offset: 0.0
        drive-steering_angle:
          axis: 2  # 2 for PS4, 3 for Logitech F710. This is actually responsible for controlling the actuator
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [5]
      message_value:
        data:
          value: 0
