# todo: pass resolution, fps and depth_module.emitter_enabled in the launch file
/**:
  ros__parameters:
#    device_type: d435i
#    camera_name: ''
#    camera_namespace: 'camera'
#    initial_reset: false
##    base_frame_id: camera_link

    accelerate_gpu_with_glsl: false  # setting to true causes high cpu utilization
    log_level: info # DEBUG|INFO|WARN|ERROR|FATAL
    wait_for_device_timeout: -1.0 # Timeout for waiting for device to connect (Seconds)
    reconnect_timeout: 6.0  # Timeout(seconds) between consecutive reconnection attempts

    enable_sync: true
    enable_color: true
    enable_depth: true
    enable_infra: true
    enable_infra1: true
    enable_infra2: true
    pointcloud.enable: true
    enable_gyro: true
    enable_accel: true
    enable_rgbd: false
    enable_confidence: true
    enable_pose: false

    rgb_camera:
      profile: "640x360x15"  # 640x360x15, 640x480x60, 848x480x30, 1280x720x30
#      color_format: bgr8
#      enable_auto_exposure: true

    depth_module:
      profile: "640x360x15"  # 640x360x15, 640x480x60, 848x480x30, 1280x720x30
      emitter_enabled: 1  # set to 0 if using infra
      emitter_on_off: false
#      infra_format: bgr8
#      enable_auto_exposure: true

#    colorizer.enable: false
    align_depth:
      enable: true

    pointcloud:
      ordered_pc: true
      stream_filter: 2  #  2=colorized pointcloud [recommended], 0=plain white pointcloud
#      stream_index_filter: 0
      allow_no_texture_points: true

#    pointcloud_texture_index: 0
#    pointcloud_texture_stream: RS2_STREAM_ANY


    gyro_fps: 200 # 200, 400
    accel_fps: 200 # 100, 200
    unite_imu_method: 2
#    angular_velocity_cov: 0.01
#    linear_accel_cov: 0.01

    publish_tf: true
    tf_publish_rate: 60.0

    # Enable post-processing filters
#    decimation_filter:
#      enable: true
#      filter_magnitude: 2
#        spatial_filter.enable: true
#    temporal_filter:
#      enable: true
#    disparity_filter:
#      enable: true
#    hole_filling_filter:
#      enable: true

    # setup sensor QoS. SYSTEM_DEFAULT [default QoS] | DEFAULT | SENSOR_DATA | PARAMETER_EVENTS | SERVICES_DEFAULT | PARAMETERS
#    color_qos: "SENSOR_DATA"
#    color_info_qos: "SENSOR_DATA"
#    infra_qos: "SENSOR_DATA"
#    infra1_qos: "SENSOR_DATA"
#    infra2_qos: "SENSOR_DATA"
#    depth_qos: "SENSOR_DATA"
#    depth_info_qos: "SENSOR_DATA"
#    pointcloud.pointcloud_qos: "SENSOR_DATA"
#    gyro_qos: "SENSOR_DATA"
#    accel_qos: "SENSOR_DATA"

