# todo: remove
/**:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 8.0 # 4.0
    publish_frequency: 8.0 # 4.0
    #set to true if you want to initialize the costmap from a static map
    static_map: true  # false

#    #begin - COMMENT these lines if you set static_map to true
    rolling_window: false # true
#    width: 10
#    height: 10
#    resolution: 0.05
#    #end - COMMENT these lines if you set static_map to true

    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: false
        transform_tolerance: 1.0
        map_topic: "/map"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: scan
      footprint_clearing_enabled: true
      max_obstacle_height: 10.0
      combination_method: 1
      scan:
        topic: /lidar/scan_filtered
        obstacle_max_range: 30.0
        obstacle_min_range: 0.0
        raytrace_max_range: 30.0
        raytrace_min_range: 0.0
        max_obstacle_height: 10.0
        min_obstacle_height: 0.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        inf_is_valid: false
        expected_update_rate: 0.13  # 0.1 (average for YDLidar is 8.626)
        observation_persistence: 0.5
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.1
      cost_scaling_factor: 1.0
      inflate_unknown: false
      inflate_around_unknown: true

